### ISSUE TITLE
attention matrix 

### ISSUE THREAD

**Issue by Tailor2019** [ihdia/docvisor#1]
Hello!
@sumanmichael @Syzygianinfern0 @cvitatma @PranavTadimeti @khadiravana-belagavi 
Thanks a lot for this great tool!
Please How can I prepare the attention matrix for an image in order to test it on the test selection for the module OCR?
Thanks a lot for your help!

**Comment by itsbvk** [comment]
You will have to use a OCR model that has the attention mechanism in it. One such model can be found [here](https://github.com/emedvedev/attention-ocr).  Once you have a model that uses attention mechanism you can extract the image co-ordinates for each character -- which is then used as input to the docvisor tool. One such example of extracting the image co-ordinates can be found [here](https://github.com/emedvedev/attention-ocr/blob/master/aocr/util/visualizations.py#L106).
